image: ruby:2.5.7

services:
  - postgres:9.5

variables:
  POSTGRES_DB: health_api_test
  POSTGRES_USER: health_api
  POSTGRES_PASSWORD: health_api
  DB_HOST: postgres

stages:
  - build
  - deploy

job_build:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --without staging production
    - RACK_ENV=test bundle exec rake

job_deploy_staging:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_STAGING_APP --api-key=$HEROKU_STAGING_API_KEY
  only:
    - staging

job_deploy_production:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_PRODUCTION_APP --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - master
