swagger: '2.0'
info:
  description: Health API
  title: Altojardin - Health API
  version: 1.0.0
host: altojardin-health-api-prod.herokuapp.com
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /covid:
    post:
      description: "Corre el test para saber si un afiliado es o no sospechoso de Covid-19"
      responses:
        200:
          description: "Devuelve el resultado del test"
          schema:
            sospechoso:
              description: "Resultado del test"
              type: boolean
  /covid/{afiliado_id}:
    parameters:
    - name: afiliado_id
      in: path
      type: string
      description: "id del Afiliado"
      required: true
    get:
      description: "Devuelve si el afiliado dio sospechoso en un test ya hecho anteriormente"
      responses:
        200:
          description: "Devuelve si anteriormente fue sospechoso en un test"
          schema:
            sospechoso:
              description: "Resultado del test"
              type: boolean
  /reset:
    post:
      description: "Elimina todos los datos de las tablas"
      responses:
        200:
          description: "Se eliminaron los datos"
        405:
          description: "No se puede eliminar datos en el ambiente de producción"
  /planes:
    get:
      description: "Obtener todos los planes médicos disponibles"
      responses:
        200:
          description: "Todos los planes"
          schema:
            properties:
              planes:
                items:
                  $ref: '#/definitions/Plan'
    post:
      description: "Dar de alta un nuevo plan médico"
      parameters:
        - description: "Datos para generar un nuevo plan"
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/PlanesCreate"
      responses:
        201:
          description: "Alta correcta"
          schema:
            properties:
              plan:
                $ref: '#/definitions/Plan'
  /planes/{plan_id}/prestaciones:
    parameters:
    - name: plan_id
      in: path
      type: string
      description: "id del Plan"
      required: true
    get:
      description: "Obtener todas las prestaciones del plan"
      responses:
        200:
          description: "Todas las prestaciones"
          schema:
            properties:
              prestaciones:
                items:
                  $ref: '#/definitions/Prestacion'
    post:
      description: "Agrega la prestacion al plan"
      parameters:
        - description: "La prestacion a Agregar"
          in: body
          name: body
          required: true
          schema:
            prestacion:
              type: string
              description: "nombre de la prestacion a agregar al plan"
      responses:
        201:
          description: "Correctamente agregado"
          schema:
            properties:
              
  /prestaciones:
    get:
      description: "Obtener todas las prestaciones"
      responses:
        200:
          description: "Todas las prestaciones"
          schema:
            properties:
              prestaciones:
                items:
                  $ref: '#/definitions/Prestacion'
    post:
      description: "Dar de alta una nueva prestación"
      parameters:
        - description: "Datos para generar ua prestación nueva"
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/PrestacionCreate"
      responses:
        201:
          description: "Alta correcta"
          schema:
            properties:
              prestacion:
                $ref: '#/definitions/Prestacion'
  /afiliados:
    get:
      description: "Obtener todos los afiliados"
      responses:
        200:
          description: "Todos los afiliados"
          schema:
            properties:
              planes:
                items:
                  $ref: '#/definitions/Afiliado'
    post:
      description: "Dar de alta un nuevo afiliado"
      parameters:
        - description: "Datos para generar un nuevo afiliado"
          in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/AfiliadosCreate"
      responses:
        201:
          description: "Alta correcta"
          schema:
            properties:
              id:
                $ref: '#/definitions/Id'
                
definitions:
  Id:
    type: integer
  PlanesCreate:
    properties:
      name:
        type: string
      costo:
        type: integer
  Plan:
    description: Plan médico
    properties:
      id:
        $ref: '#/definitions/Id'
      name:
        type: string
  AfiliadosCreate:
    properties:
      nombre:
        type: string
      nombre_plan:
        type: string
      id_telegram:
        type: string
  Afiliado:
    description: Afiliado
    properties:
      id:
        $ref: '#/definitions/Id'
      name:
        type: string
      plan_id:
        type: integer
      id_telegram:
        type: string  
  PrestacionCreate:
    properties:
      nombre:
        type: string
      costo:
        type: integer
  Prestacion:
    description: Prestacion médica
    properties:
      id:
        $ref: '#/definitions/Id'
      name:
        type: string
      costo: integer

